### ISSUE TITLE
Round off the Indicatieve herstelkosten to hundreds

### ISSUE THREAD

**Issue by DonZandbergen** [Laixer/FunderMapsCustomerPortal#5]
Round off the Indicatieve herstelkosten to hundreds

![image](https://user-images.githubusercontent.com/46600362/94821210-a256ad80-0401-11eb-9b69-bd54831eaeb6.png)

=> 28.700 euro.

**Comment by pnobbe** [comment]
Do we want to do this in the frontend temporarily or wait for a backend enhancement? @yorickdewid @tabeckers

**Comment by yorickdewid** [comment]
Fixed in https://github.com/Laixer/FunderMaps/issues/305
